[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "library-stats"
version = "0.1.0"

[dependencies]
atomicwrites = "0.4.3"
chrono = "0.4.31"
handlebars = "5.0.0"
serde = "1.0.195"
serde_derive = "1.0.195"
sqlite = "0.32.0"
