[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "library-stats"
version = "0.1.0"

[dependencies]
atomicwrites = "0.4.1"
chrono = "0.4.26"
handlebars = "4.3.7"
serde = "1.0.171"
serde_derive = "1.0.171"
sqlite = "0.27.0"
