[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "library-stats"
version = "0.1.0"

[dependencies]
atomicwrites = "0.3.1"
chrono = "0.4.22"
handlebars = "4.3.5"
serde = "1.0.145"
serde_derive = "1.0.145"
sqlite = "0.27.0"
