[package]
authors = ["Colin Benner <colin@yzhs.de>"]
name = "library-stats"
version = "0.1.0"

[dependencies]
atomicwrites = "0.3.1"
chrono = "0.4.22"
handlebars = "4.3.4"
serde = "1.0.144"
serde_derive = "1.0.144"
sqlite = "0.27.0"
